const basket = [
    // {
    //     id: 's1',
    //     image: 'test.webp',
    //     brand: 'Nike',
    //     model: 'Air Jordan 1',
    //     type: 'Mid',
    //     name: 'Smoke Grey',
    //     price: 9000,
    //     size: 40,
    //     renderedSize: "EU 42",
    //     count: 1,
    // },
    // {
    //     id: 's3',
    //     image: 'test.webp',
    //     brand: 'Nike',
    //     model: 'Air Jordan 1',
    //     type: 'Mid',
    //     name: 'White Shadow',
    //     price: 9500,
    //     size: 42,
    //     count: 1,
    // },
    // {
    //     id: 's5',
    //     image: 'test.webp',
    //     brand: 'New Balance',
    //     model: '530',
    //     type: '',
    //     name: '',
    //     price: 10000,
    //     size: 37,
    //     count: 1,
    // },
    // {
    //     id: 's10',
    //     image: 'test.webp',
    //     brand: 'New Balance',
    //     model: '574',
    //     type: '',
    //     name: 'Archive',
    //     price: 8000,
    //     size: 44,
    //     count: 1,
    // },
];

export default basket;
