const items = [
    {
        id: 's0',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'Nike',
        model: 'Air Jordan 1',
        type: 'Mid',
        name: 'Dark Mocha',
        colors: ['white', 'black', 'brown'],
        article: 'DJ3911-101',
        price: 13000,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
        ],
        description:
            'Женские кроссовки Air Jordan 1 Low OG Wmns Neutral Grey от американского бренда Nike. Модель определенно является лучшим вариантом для теплых летних вечеров, адаптированная специально для девушек. Основа кроссовок выполнена из высококачественной кожи белого цвета. Дизайн Air Jordan 1 Low OG Wmns Neutral Grey дополнен фирменным логотипом Wings на задней части обуви и свуши из мягкой замши в нейтральном сером оттенке, расположенные на боковых панелях кроссовок.Женские кроссовки Air Jordan 1 Low OG Wmns Neutral Grey от американского бренда Nike. Модель определенно является лучшим вариантом для теплых летних вечеров, адаптированная специально для девушек. Основа кроссовок выполнена из высококачественной кожи белого цвета. Дизайн Air Jordan 1 Low OG Wmns Neutral Grey дополнен фирменным логотипом Wings на задней части обуви и свуши из мягкой замши в нейтральном сером оттенке, расположенные на боковых панелях кроссовок.',
    },
    {
        id: 's1',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'Nike',
        model: 'Air Jordan 1',
        type: 'Mid',
        name: 'Smoke Grey',
        colors: ['white', 'grey'],
        article: 'DJ2311-101',
        price: 8000,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
    {
        id: 's2',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'Nike',
        model: 'Air Jordan 1',
        type: 'Mid',
        name: 'Pine Green',
        colors: ['white', 'black', 'green'],
        article: 'DJ2911-151',
        price: 15200,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
    {
        id: 's3',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'Nike',
        model: 'Air Jordan 1',
        type: 'Mid',
        name: 'White Shadow',
        colors: ['white', 'black', 'grey'],
        article: 'DJ3111-101',
        price: 12500,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
    {
        id: 's4',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'Nike',
        model: 'Air Jordan 1',
        type: 'Low',
        name: 'Canyon Rust',
        colors: ['red', 'black', 'beige'],
        article: 'DF4211-101',
        price: 15700,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
    {
        id: 's5',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'New Balance',
        model: '530',
        type: '',
        name: '',
        colors: ['white', 'black', 'grey'],
        article: 'MR530SG/D',
        price: 7000,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
    {
        id: 's6',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'New Balance',
        model: '574',
        type: '',
        name: 'Mid',
        colors: ['beige', 'black'],
        article: 'WH574MD2/B',
        price: 12000,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
    {
        id: 's7',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'New Balance',
        model: 'Fresh Foam Hierro v7',
        type: '',
        name: '',
        colors: ['brown', 'green', 'orange'],
        article: 'MTHIERG7/D',
        price: 13200,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
    {
        id: 's8',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'New Balance',
        model: '574',
        type: '',
        name: 'Classic',
        colors: ['blue', 'black', 'red', 'white'],
        article: 'ML574IX2/D',
        price: 6700,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
    {
        id: 's9',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'New Balance',
        model: '574',
        type: '',
        name: 'Evergreen',
        colors: ['white', 'black', 'grey'],
        article: 'ML574EVB/D',
        price: 16300,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
    {
        id: 's10',
        image: 'test.webp',
        category: 'Кроссовки',
        brand: 'New Balance',
        model: '574',
        type: '',
        name: 'Archive',
        colors: ['white', 'blue', 'yellow'],
        article: 'ML574TE/D',
        price: 20990,
        sizes: [
            { size: 37, amount: 10000 },
            { size: 40, amount: 9000 },
            { size: 42, amount: 9500 },
            { size: 44, amount: 8000 },
        ],
        description: 'qwerty',
    },
];

export default items;
