const items = [
  {
    id: 's0',
    title: 'Кроссовки Nike Air Jordan 1 Mid Sea’s Deep',
    // image: '',
    description: 'qwerty',
    price: 10000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's1',
    title: 'Adidas',
    // image: '',
    description: 'asdfg',
    price: 20000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's2',
    title: 'Reebok',
    // image: '',
    description: 'zxcvb',
    price: 30000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's3',
    title: 'NewBalance',
    // image: '',
    description: 'ypoiu',
    price: 50000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's4',
    title: 'Puma',
    // image: '',
    description: 'lkjhgfd',
    price: 40000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's3',
    title: 'NewBalance',
    // image: '',
    description: 'ypoiu',
    price: 50000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's4',
    title: 'Puma',
    // image: '',
    description: 'lkjhgfd',
    price: 40000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's3',
    title: 'NewBalance',
    // image: '',
    description: 'ypoiu',
    price: 50000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's4',
    title: 'Puma',
    // image: '',
    description: 'lkjhgfd',
    price: 40000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's3',
    title: 'NewBalance',
    // image: '',
    description: 'ypoiu',
    price: 50000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
  {
    id: 's4',
    title: 'Puma',
    // image: '',
    description: 'lkjhgfd',
    price: 40000,
    article: 'DJ3911-101',
    colors: 'white/black/orange',
  },
];

export default items;