# Generated by Django 4.2 on 2023-06-14 15:45

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footwear',
            options={'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AlterModelOptions(
            name='footwearinstance',
            options={'verbose_name': 'Экземпляр', 'verbose_name_plural': 'Экземпляры'},
        ),
        migrations.RenameField(
            model_name='footwear',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='footwearinstance',
            old_name='sneaker',
            new_name='footwear',
        ),
        migrations.RemoveField(
            model_name='footwearcategory',
            name='brand',
        ),
        migrations.AddField(
            model_name='footwear',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='colors',
            field=api.models.ColorArrayField(base_field=models.CharField(choices=[('black', 'Черный'), ('white', 'Белый'), ('green', 'Зеленый'), ('purple', 'Фиолетовый'), ('red', 'Красный'), ('yellow', 'Желтый'), ('brown', 'Коричневый'), ('grey', 'Серый'), ('pink', 'Розовый'), ('blue', 'Синий'), ('orange', 'Оранжевый')], max_length=15), size=None, verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='gender',
            field=models.CharField(choices=[('U', 'Унисекс'), ('M', 'Мужской'), ('W', 'Женский')], default='U', max_length=1, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('footwear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.footwear', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='FootwearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.AlterField(
            model_name='footwear',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.footwearmodel', verbose_name='Модель'),
        ),
    ]
